### PR TITLE
feat: change pathname from /builder to /editor

### PR DESCRIPTION
**Pull request by thewbuk**
Because

- To maintain consistency in terminology, the "builder" URL should be replaced with "editor" 

INFO:

- The documentation is **NOT** updated for the most part
- The internal structure is **NOT** updated for the most part

### CODE REVIEW

**Comment by EiffelFly** [comment]
@thewbuk To unify naming, we need to change all the "builder" naming in this repo to "editor"

**Comment by thewbuk** [comment]
> @thewbuk To unify naming, we need to change all the "builder" naming in this repo to "editor"

@EiffelFly I can easily take care of documentation as well but do You mean renaming all components like `PipelineBuilderPage` or `PipelineListPage` and all functions like `deletePipeline` to the editor standard? In that case that's 100s of references throughout the repo. Do You want to address this in this PR or the following one?

**Comment by EiffelFly** [comment]
@thewbuk That is a good point, let just make it work in this PR and address this in another PR, so we can do it slowly. Please rebase main then I think we can merge this PR

**Comment by orangecoloured** [comment]
@thewbuk all seems fine, but for this button

Screenshot 2024-06-14 at 11 18 47 PM

**Review by EiffelFly — APPROVED** [review]
LGTM

**Pull request merged**
