### PR TITLE
fix(organization): update UploadAvatarFieldWithCrop component to accept title props

### PR DESCRIPTION
**Pull request by iamnamananand996**
Because

-  update UploadAvatarFieldWithCrop component

This commit

- update UploadAvatarFieldWithCrop component

### CODE REVIEW

**Comment by EiffelFly** [comment]
@iamnamananand996 I think you misunderstand the issue. The issue is, when you upload the user profile image, there will be a dialog for you to crop the image. We also need that for user to upload their organization profile image

**Comment by iamnamananand996** [comment]
> @iamnamananand996 I think you misunderstand the issue. The issue is, when you upload the user profile image, there will be a dialog for you to crop the image. We also need that for user to upload their organization profile image

Hi @EiffelFly, you are correct, the main PR is created here, https://github.com/instill-ai/console-cloud/pull/520
because this is only for organization profile.

this PR is only for small changes i.e, we can also pass **title** to `UploadAvatarFieldWithCrop`

**Comment by EiffelFly** [comment]
@iamnamananand996 Got it, sorry that I didn't notice this 🦤

**Review by EiffelFly — APPROVED** [review]
LGTM

**Pull request merged**
